install.packages("caTools")
set.seed(0)
split=sample.split(df,SplitRatio = 0.8)
training_set=subset(df,split==TRUE)
test_set=subset(df,split==FALSE)
lm_a=lm(price~.,data=training_set)
summary(lm_a)
train_a=predict(lm_a,training_set)
test_a=predict(lm_a,test_set)
msetrain=mean((training_set$price-train_a)^2)
msetest=mean((test_set$price-test_a)^2)
